"""Secure markdown report creation tool with confirmation enforcement."""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from app.core.config import settings
from app.tools.base import BaseTool, PermissionLevel, ToolContext
from app.tools.builtin.file_search import get_allowed_dir, validate_sandboxed_path

logger = logging.getLogger("nova.tools.create_report")


class CreateReportInput(BaseModel):
    """Input parameters for report generation."""

    title: str = Field(description="Title of the report")
    content: str = Field(description="Markdown-formatted body of the report")
    filename: str | None = Field(
        default=None,
        description="Optional custom file name without extension (e.g. 'quarterly-summary')",
    )


def sanitize_filename(name: str) -> str:
    """Sanitize filename to prevent directory traversal or invalid characters."""
    clean = re.sub(r"[^a-zA-Z0-9_\-]", "_", name.strip())
    return clean.strip("_") or "report"


class CreateReportTool(BaseTool):
    """Creates a structured Markdown report in the designated reports folder.

    Marked as MEDIUM risk because it writes files to disk, requiring explicit confirmation.
    """

    name = "create_report"
    description = (
        "Write and save a structured Markdown report to the designated reports output directory. "
        "Requires explicit user confirmation before creation."
    )
    input_schema = CreateReportInput
    permission_level = PermissionLevel.MEDIUM
    timeout_seconds = 10.0

    async def execute(self, params: CreateReportInput, context: ToolContext | None = None) -> dict[str, Any]:
        allowed_root = get_allowed_dir()
        reports_dir = Path(settings.reports_dir).resolve()

        # Ensure reports dir is within allowed sandbox
        safe_reports_dir = validate_sandboxed_path(reports_dir, allowed_root)
        safe_reports_dir.mkdir(parents=True, exist_ok=True)

        # Generate safe filename
        if params.filename:
            base_name = sanitize_filename(params.filename)
        else:
            base_name = sanitize_filename(params.title)

        timestamp_str = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        target_filename = f"{base_name}_{timestamp_str}.md"
        target_path = safe_reports_dir / target_filename
        safe_file_path = validate_sandboxed_path(target_path, allowed_root)
        if safe_file_path.exists() or safe_file_path.is_symlink():
            raise FileExistsError(f"Report target '{target_filename}' already exists.")

        # Build full markdown document
        now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        markdown_body = (
            f"# {params.title.strip()}\n\n"
            f"*Generated by NOVA Autonomous Assistant on {now_iso}*\n\n"
            "---\n\n"
            f"{params.content.strip()}\n"
        )

        safe_file_path.write_text(markdown_body, encoding="utf-8")
        rel_path = safe_file_path.relative_to(allowed_root).as_posix()

        logger.info("report successfully created at: %s", rel_path)
        return {
            "title": params.title,
            "filename": target_filename,
            # Keep both paths: ``file_path`` is convenient for local callers,
            # while ``relative_path`` avoids exposing the sandbox root in UI.
            "file_path": str(safe_file_path),
            "relative_path": rel_path,
            "bytes_written": len(markdown_body.encode("utf-8")),
            "status": "created",
        }
